<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>cn.sliew</groupId>
    <artifactId>scaleph</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>scaleph</name>
    <description>Scaleph System</description>
    <url>https://github.com/flowerfine/scaleph</url>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>git@github.com:flowerfine/scaleph.git</connection>
        <developerConnection>scm:git:git@github.com:flowerfine/scaleph.git</developerConnection>
        <url>https://github.com/flowerfine/scaleph</url>
        <tag>HEAD</tag>
    </scm>

    <developers>
        <developer>
            <name>kalencaya</name>
            <email>1942460489@qq.com</email>
        </developer>
        <developer>
            <name>gleiyu</name>
            <email>gleiyu@sina.cn</email>
        </developer>
        <developer>
            <name>LiuBodong</name>
            <email>liubodong2010@126.com</email>
        </developer>
    </developers>

    <issueManagement>
        <system>Github Issue</system>
        <url>https://github.com/flowerfine/scaleph/issues</url>
    </issueManagement>

    <distributionManagement>
        <snapshotRepository>
            <id>sonatype-nexus</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>sonatype-nexus</id>
            <name>Sonatype Nexus Release</name>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>

    <modules>
        <module>scaleph-ui-react</module>
        <module>scaleph-ui-react2</module>

        <module>scaleph-dependencies</module>
        <module>scaleph-common</module>
        <module>scaleph-dao</module>
        <module>scaleph-security</module>
        <module>scaleph-resource</module>
        <module>scaleph-support</module>
        <module>scaleph-config</module>
        <module>scaleph-api</module>
        <module>scaleph-meta</module>

        <module>scaleph-application</module>
        <module>scaleph-engine</module>
        <module>scaleph-workspace</module>
        <module>scaleph-plugins</module>
        <module>scaleph-workflow</module>
        <module>scaleph-datasource</module>
        <module>scaleph-kubernetes</module>

        <module>scaleph-dist</module>
        <module>scaleph-file-fetcher</module>
        <module>scaleph-dataservice</module>
    </modules>

    <properties>
        <revision>2.0.6-SNAPSHOT</revision>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.encoding>UTF-8</maven.compiler.encoding>
        <scala.binary.version>2.12</scala.binary.version>
        <java.version>17</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>

        <maven.test.skip>true</maven.test.skip>
        <maven.deploy.skip>false</maven.deploy.skip>
        <flatten-maven-plugin.version>1.6.0</flatten-maven-plugin.version>
        <mapstruct.version>1.4.2.Final</mapstruct.version>
        <mapstruct.extensions.spring.version>0.1.1</mapstruct.extensions.spring.version>
        <mapstruct.lombok.binding.version>0.2.0</mapstruct.lombok.binding.version>
        <lombok.version>1.18.38</lombok.version>
        <auto-service.version>1.1.1</auto-service.version>
        <pf4j.version>3.12.1</pf4j.version>
    </properties>

    <build>
        <finalName>${project.artifactId}</finalName>
        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <includes>
                    <include>META-INF/**/*</include>
                    <include>**/*.yml</include>
                    <include>**/*.xml</include>
                    <include>**/*.properties</include>
                    <include>**/*.conf</include>
                    <include>**/*.html</include>
                    <include>**/*.js</include>
                    <include>**/*.css</include>
                    <include>**/*.eot</include>
                    <include>**/*.ttf</include>
                    <include>**/*.woff</include>
                    <include>**/*.svg</include>
                    <include>**/*.png</include>
                    <include>**/*.ico</include>
                    <include>**/*.ico</include>
                    <include>**/*.json</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>${maven.compiler.encoding}</encoding>
                    <!-- 不加此参数，编译的方法会丢失方法名，反射无法通过 name 获取到参数名，只能拿到 arg0 这种 -->
                    <!-- 导致所有依赖反射获取方法名的功能都无法使用，比如 mybatis 方法都需要指定 @Param -->
                    <!-- @Controller 都需要指定 @PathVariable、@RequestParam，aop 需要添加 argNames = 'name' -->
                    <!-- 如 say(String name) -> say(String arg0) -->
                    <parameters>true</parameters>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${mapstruct.lombok.binding.version}</version>
                        </path>
                        <path>
                            <groupId>com.google.auto.service</groupId>
                            <artifactId>auto-service</artifactId>
                            <version>${auto-service.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>