export const PRIVILEGE_CODE = {
  studioShow: 'psdo0',
  studioDataBoardShow: 'psdb0',

  projectShow: 'pddp0',
  datadevProjectSelect: 'pddp4',
  datadevProjectAdd: 'pddp1',
  datadevProjectDelete: 'pddp3',
  datadevProjectEdit: 'pddp2',

  workspaceShow: 'pdev0',
  workspaceJobShow: 'pddj0',
  workspaceJobDetailShow: 'pddj0',
  workspaceJobArtifactShow: 'pddj0',
  workspaceJobArtifactJarShow: 'pddj0',
  workspaceJobSqlShow: 'pddj0',
  workspaceJobSeaTunnelShow: 'pddj0',
  workspaceClusterShow: 'pddj0',
  workspaceClusterConfigShow: 'pddj0',
  workspaceClusterConfigOptionsShow: 'pddj0',
  workspaceClusterInstanceShow: 'pddj0',

  resourceShow: 'pddj0',
  resourceJarShow: 'pddj0',
  resourceFlinkReleaseShow: 'pddj0',
  resourceSeaTunnelReleaseShow: 'pddj0',
  resourceKerberosShow: 'pddj0',
  resourceClusterCredentialShow: 'pddj0',

  dataSourceShow: 'pddj0',
  datadevDatasourceSelect: 'pdts4',
  datadevDatasourceAdd: 'pdts1',
  datadevDatasourceDelete: 'pdts3',
  datadevDatasourceEdit: 'pdts2',
  datadevDatasourceSecurity: 'pdts6',

  stdataShow: 'pstd0',
  stdataRefDataShow: 'pstr0',
  stdataRefDataMapShow: 'pstm0',
  stdataDataElementShow: 'pste0',
  stdataSystemShow: 'psts0',



  datadevResourceSelect: 'pdde4',
  datadevResourceAdd: 'pdde1',
  datadevResourceDelete: 'pdde3',
  datadevResourceEdit: 'pdde2',
  datadevResourceDownload: 'pdde7',
  datadevJobSelect: 'pddj4',
  datadevJobAdd: 'pddj1',
  datadevJobDelete: 'pddj3',
  datadevJobEdit: 'pddj2',
  datadevDirSelect: 'pddr4',
  datadevDirAdd: 'pddr1',
  datadevDirDelete: 'pddr3',
  datadevDirEdit: 'pddr2',
  datadevClusterSelect: 'pddc4',
  datadevClusterAdd: 'pddc1',
  datadevClusterDelete: 'pddc3',
  datadevClusterEdit: 'pddc2',
  opscenterBatchSelect: 'pobt4',
  opscenterRealtimeSelect: 'port4',
  stdataRefDataTypeSelect: 'pstt4',
  stdataRefDataTypeAdd: 'pstt1',
  stdataRefDataTypeDelete: 'pstt3',
  stdataRefDataTypeEdit: 'pstt2',
  stdataRefDataSelect: 'pstr4',
  stdataRefDataAdd: 'pstr1',
  stdataRefDataDelete: 'pstr3',
  stdataRefDataEdit: 'pstr2',
  stdataRefDataMapSelect: 'pstm4',
  stdataRefDataMapAdd: 'pstm1',
  stdataRefDataMapDelete: 'pstm3',
  stdataRefDataMapEdit: 'pstm2',
  stdataDataElementSelect: 'pste4',
  stdataDataElementAdd: 'pste1',
  stdataDataElementDelete: 'pste3',
  stdataDataElementEdit: 'pste2',
  stdataSystemSelect: 'psts4',
  stdataSystemAdd: 'psts1',
  stdataSystemDelete: 'psts3',
  stdataSystemEdit: 'psts2',


  adminShow: 'padm0',
  deptShow: 'padp0',
  deptAdd: 'padp1',
  deptEdit: 'padp2',
  deptDelete: 'padp3',
  deptSelect: 'padp4',
  deptGrant: 'padp5',

  roleShow: 'padr0',
  roleAdd: 'padr1',
  roleEdit: 'padr2',
  roleDelete: 'padr3',
  roleSelect: 'padr4',
  roleGrant: 'padr5',

  userShow: 'padu0',
  resourceWebShow: 'parw0',
  privilegeShow: 'pape0',
  workflowQuartzShow: 'pawq0',
  dictShow: 'padd0',
  settingShow: 'pads0',

  userSelect: 'pusr4',
  userAdd: 'pusr1',
  userDelete: 'pusr3',
  userEdit: 'pusr2',


  dictTypeSelect: 'pdct4',
  dictTypeAdd: 'pdct1',
  dictTypeDelete: 'pdct3',
  dictTypeEdit: 'pdct2',
  dictDataSelect: 'pdcd4',
  dictDataAdd: 'pdcd1',
  dictDataDelete: 'pdcd3',
  dictDataEdit: 'pdcd2',
};
