import { PRIVILEGE_CODE } from '../src/constant';

export default [
  {
    path: '/',
    redirect: '/studio/databoard',
  },
  {
    path: '/login',
    layout: false,
    component: './User/Login',
  },
  {
    path: '/register',
    layout: false,
    component: './User/Register',
  },
  {
    path: '/user/center',
    component: './User',
  },
  {
    name: 'studio',
    path: '/studio',
    icon: 'codeSandbox',
    pCode: PRIVILEGE_CODE.studioShow,
    access: 'normalRouteFilter',
    routes: [
      {
        path: '/studio',
        redirect: '/studio/databoard',
        pCode: PRIVILEGE_CODE.studioShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'databoard',
        path: '/studio/databoard',
        icon: 'dashboard',
        exact: true,
        component: './Studio/DataBoard',
        pCode: PRIVILEGE_CODE.studioDataBoardShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'project',
        path: '/studio/project',
        icon: 'project',
        exact: true,
        component: './Studio/Project',
        pCode: PRIVILEGE_CODE.datadevProjectShow,
        access: 'normalRouteFilter',
      },
    ],
  },
  {
    name: 'workspace',
    path: '/workspace',
    icon: 'project',
    pCode: PRIVILEGE_CODE.datadevProjectShow,
    routes: [
      {
        path: '/workspace',
        exact: true,
        component: './Studio/Project',
        pCode: PRIVILEGE_CODE.datadevProjectShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'databoard',
        path: '/workspace/databoard',
        icon: 'dashboard',
        exact: true,
        component: './Studio/DataBoard',
        pCode: PRIVILEGE_CODE.studioDataBoardShow,
        access: 'normalRouteFilter',
      },
      // {
      //   name: 'project',
      //   path: '/studio/project',
      //   icon: 'project',
      //   exact: true,
      //   component: './Studio/Project',
      //   pCode: PRIVILEGE_CODE.datadevProjectShow,
      //   access: 'normalRouteFilter',
      // },
    ],
  },
  {
    name: 'datadev',
    path: '/datadev',
    icon: 'desktop',
    pCode: PRIVILEGE_CODE.datadevShow,
    access: 'normalRouteFilter',
    routes: [
      {
        path: '/datadev',
        redirect: '/datadev/datasource',
        pCode: PRIVILEGE_CODE.datadevShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'datasource',
        path: '/datadev/datasource',
        icon: 'link',
        exact: true,
        component: './DI/DataSource',
        pCode: PRIVILEGE_CODE.datadevResourceShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'resource',
        path: '/datadev/resource',
        icon: 'fileText',
        exact: true,
        component: './DI/Resource',
        pCode: PRIVILEGE_CODE.datadevResourceShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'cluster',
        path: '/datadev/cluster',
        icon: 'cluster',
        exact: true,
        component: './DI/Cluster',
        pCode: PRIVILEGE_CODE.datadevClusterShow,
        access: 'normalRouteFilter',
      },
    ],
  },
  {
    name: 'opscenter',
    path: '/opscenter',
    icon: 'lineChart',
    pCode: PRIVILEGE_CODE.opscenterShow,
    access: 'normalRouteFilter',
    routes: [
      {
        path: '/opscenter',
        redirect: '/opscenter/batch',
        pCode: PRIVILEGE_CODE.opscenterShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'batch',
        path: '/opscenter/batch',
        icon: 'menu',
        exact: true,
        component: './OpsCenter/BatchJob',
        pCode: PRIVILEGE_CODE.opscenterBatchShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'realtime',
        path: '/opscenter/realtime',
        icon: 'menu',
        exact: true,
        component: './OpsCenter/RealtimeJob',
        pCode: PRIVILEGE_CODE.opscenterRealtimeShow,
        access: 'normalRouteFilter',
      },
    ],
  },
  {
    name: 'stdata',
    path: '/stdata',
    icon: 'database',
    pCode: PRIVILEGE_CODE.stdataShow,
    access: 'normalRouteFilter',
    routes: [
      {
        path: '/stdata',
        redirect: '/stdata/dataElement',
        pCode: PRIVILEGE_CODE.stdataShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'dataElement',
        path: '/stdata/dataElement',
        icon: 'menu',
        exact: true,
        component: './Stdata/DataElement',
        pCode: PRIVILEGE_CODE.stdataDataElementShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'refdata',
        path: '/stdata/refdata',
        icon: 'menu',
        exact: true,
        component: './Stdata/RefData',
        pCode: PRIVILEGE_CODE.stdataRefDataShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'refdataMap',
        path: '/stdata/refdataMap',
        icon: 'menu',
        exact: true,
        component: './Stdata/RefDataMap',
        pCode: PRIVILEGE_CODE.stdataRefDataMapShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'system',
        path: '/stdata/system',
        icon: 'menu',
        exact: true,
        component: './Stdata/System',
        pCode: PRIVILEGE_CODE.stdataSystemShow,
        access: 'normalRouteFilter',
      },
    ],
  },
  {
    name: 'admin',
    path: '/admin',
    icon: 'setting',
    pCode: PRIVILEGE_CODE.adminShow,
    access: 'normalRouteFilter',
    routes: [
      {
        path: '/admin',
        redirect: '/admin/user',
        pCode: PRIVILEGE_CODE.adminShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'user',
        path: '/admin/user',
        icon: 'user',
        exact: true,
        component: './Admin/User',
        pCode: PRIVILEGE_CODE.userShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'privilege',
        path: '/admin/privilege',
        icon: 'team',
        exact: true,
        component: './Admin/Privilege',
        pCode: PRIVILEGE_CODE.privilegeShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'dict',
        path: '/admin/dict',
        icon: 'table',
        exact: true,
        component: './Admin/Dict',
        pCode: PRIVILEGE_CODE.dictShow,
        access: 'normalRouteFilter',
      },
      {
        name: 'setting',
        path: '/admin/setting',
        icon: 'setting',
        exact: true,
        component: './Admin/Setting',
        pCode: PRIVILEGE_CODE.settingShow,
        access: 'normalRouteFilter',
      },
    ],
  },
  {
    component: './404',
  },
];
