export const DICT_TYPE = {
  yesNo: 'yes_or_no',

  carpSecApplicationType: 'sec_application_type',
  carpSecApplicationStatus: 'sec_application_status',
  carpSecRoleType: 'sec_role_type',
  carpSecRoleStatus: 'sec_role_status',
  carpSecUserType: 'sec_user_type',
  carpSecUserStatus: 'sec_user_status',
  carpSecResourceWebType: 'sec_resource_web_type',
  carpSecResourceDataType: 'sec_resource_data_type',
  carpSecResourceStatus: 'sec_resource_status',

  carpDataSourceType: 'datasource_type',
  carpDataSourceRedisMode: 'datasource_redis_mode',

  roleType: 'role_type',
  roleStatus: 'role_status',
  userType: 'user_type',
  userStatus: 'user_status',
  deptStatus: 'dept_status',
  resourceType: 'resource_type',

  idCardType: 'id_card_type',
  gender: 'gender',
  nation: 'nation',

  datasourceType: 'datasource_type',
  redisMode: 'redis_mode',

  jobType: 'job_type',
  jobStatus: 'job_status',
  jobInstanceState: 'job_instance_state',
  runtimeState: 'runtime_state',
  clusterType: 'cluster_type',
  dataType: 'data_type',
  flinkRuntimeExecutionMode: 'flink_runtime_execution_mode',
  flinkDeployConfigType: 'flink_deploy_config_type',
  flinkResourceProvider: 'flink_resource_provider',
  flinkDeploymentMode: 'flink_deployment_mode',
  flinkVersion: 'flink_version',
  flinkStateBackend: 'flink_state_backend',
  flinkClusterStatus: 'flink_cluster_status',
  flinkSemantic: 'flink_semantic',
  flinkCheckpointRetain: 'flink_checkpoint_retain',
  flinkRestartStrategy: 'flink_restart_strategy',
  flinkHA: 'flink_high_availability',
  flinkJobType: 'flink_job_type',
  flinkJobStatus: 'flink_job_status',
  flinkServiceExposedType: 'flink_service_exposed_type',

  seatunnelVersion: 'seatunnel_version',
  seatunnelEngineType: 'seatunnel_engine_type',
  seatunnelPluginName: 'seatunnel_plugin_name',
  seatunnelRowKind: 'seatunnel_row_kind',
  seatunnelFakeMode: 'seatunnel_fake_mode',
  seatunnelCDCFormat: 'seatunnel_cdc_format',
  imagePullPolicy: 'image_pull_policy',

  flinkCDCVersion: 'flink_cdc_version',

  deploymentKind: 'deployment_kind',
  resourceLifecycleState: 'resource_lifecycle_state',
  upgradeMode: 'upgrade_mode',
};
