// const DictType = enummapping({
//   YES_OR_NO: {value: "yes_or_no", label: "是否"},
//   IS_DELETED: {value: "is_delete", label: "是否删除"},
//   GENDER: {value: "gender", label: "性别"},
//   ID_CARD_TYPE: {value: "id_card_type", label: "证件类型"},
//   NATION: {value: "nation", label: "国家"},
//   MESSAGE_TYPE: {value: "message_type", label: "消息类型"},
//   REGISTER_CHANNEL: {value: "register_channel", label: "注册渠道"},
//   LOGIN_TYPE: {value: "login_type", label: "登录类型"},
//   USER_TYPE: {value: "user_type", label: "用户类型"},
//   USER_STATUS: {value: "user_status", label: "用户状态"},
//   ROLE_TYPE: {value: "role_type", label: "角色类型"},
//   ROLE_STATUS: {value: "role_status", label: "角色状态"},
//   DEPT_STATUS: {value: "dept_status", label: "部门状态"},
//   RESOURCE_TYPE: {value: "resource_type", label: "权限资源类型"},
//   TASK_RESULT: {value: "task_result", label: "任务运行结果"},
//   DATASOURCE_TYPE: {value: "datasource_type", label: "数据源类型"},
//   JOB_STATUS: {value: "job_status", label: "作业状态"},
//   JOB_INSTANCE_TYPE: {value: "job_instance_state", label: "作业实例状态"},
//   RUNTIME_STATE: {value: "runtime_state", label: "运行状态"},
//   JOB_ATTR_TYPE: {value: "job_attr_type", label: "作业属性类型"},
//   CLUSTER_TYPE: {value: "cluster_type", label: "集群类型"},
//   DATA_TYPE: {value: "data_type", label: "数据类型"},
//   FLINK_VERSION: {value: "flink_version", label: "Flink 版本"},
//   FLINK_RESOURCE_PROVIDER: {value: "flink_resource_provider", label: "Flink 资源类型"},
//   FLINK_DEPLOYMENT_MODE: {value: "flink_deployment_mode", label: "Flink 部署模式"},
//   FLINK_RUNTIME_EXECUTION_MODE: {value: "flink_runtime_execution_mode", label: "Flink 运行模式"},
//   FLINK_HIGH_AVAILABILITY: {value: "flink_high_availability", label: "Flink HA"},
//   FLINK_RESTART_STRATEGY: {value: "flink_restart_strategy", label: "Flink 重启策略"},
//   FLINK_STATE_BACKEND: {value: "flink_state_backend", label: "Flink State Backend"},
//   FLINK_CHECKPOINT_RETAIN: {value: "flink_checkpoint_retain", label: "Flink 外部 checkpoint 保留模式"},
//   FLINK_SEMANTIC: {value: "flink_semantic", label: "Flink 时间语义"},
//   FLINK_CLUSTER_STATUS: {value: "flink_cluster_status", label: "Flink 集群状态"},
//   FLINK_JOB_STATUS: {value: "flink_job_status", label: "Flink 任务状态"},
//   FLINK_JOB_TYPE: {value: "flink_job_type", label: "Flink 任务类型"},
//   FLINK_SAVEPOINT_TYPE: {value: "flink_savepoint_type", label: "Flink Savepoint 类型"},
//   FLINK_KUBERNETES_DEPLOYMENT_MODE: {value: "deployment_mode", label: "Deployment 模式"},
//   FLINK_KUBERNETES_DEPLOYMENT_KIND: {value: "deployment_kind", label: "Deployment 类型"},
//   FLINK_KUBERNETES_OPERATOR_FLINK_VERSION: {
//     value: "operator_flink_version",
//     label: "Flink Kubernetes Operator Flink 版本"
//   },
//   FLINK_KUBERNETES_RESOURCE_LIFECYCLE_STATE: {value: "resource_lifecycle_state", label: "Deployment 状态"},
//   FLINK_KUBERNETES_UPGRADE_MODE: {value: "upgrade_mode", label: "Upgrade 方式"},
//   FLINK_KUBERNETES_SAVEPOINT_FORMAT_TYPE: {value: "savepoint_format_type", label: "Savepoint Format 类型"},
//   FLINK_KUBERNETES_SAVEPOINT_TRIGGER_TYPE: {value: "savepoint_trigger_type", label: "Savepoint Trigger 类型"},
//   FLINK_CATALOG_COLUMN_TYPE: {value: "flink_catalog_column_type", label: "Flink Catalog Table Schema 列类型"},
//   FLINK_CATALOG_TABLE_KIND: {value: "flink_catalog_table_kind", label: "Flink Catalog Table 类型"},
//   FLINK_CATALOG_CONSTRAINT_TYPE: {value: "flink_catalog_constraint_type", label: "Flink Catalog Table Constraint 类型"},
//   FLINK_CATALOG_FUNCTION_LANGUAGE: {value: "flink_catalog_function_language", label: "Flink Catalog Function 语言"},
//   SEATUNNEL_VERSION: {value: "seatunnel_version", label: "SeaTunnel 版本"},
//   SEATUNNEL_ENGINE_TYPE: {value: "seatunnel_engine_type", label: "SeaTunnel 引擎类型"},
//   SEATUNNEL_PLUGIN_TYPE: {value: "seatunnel_plugin_type", label: "SeaTunnel 插件类型"},
//   SEATUNNEL_PLUGIN_NAME: {value: "seatunnel_plugin_name", label: "SeaTunnel 插件名称"},
//   SEATUNNEL_CONNECTOR_FEATURE: {value: "seatunnel_connector_feature", label: "SeaTunnel connector 特性"},
//   SEATUNNEL_CONNECTOR_HEALTH: {value: "seatunnel_connector_health", label: "SeaTunnel connector 成熟度"},
//   SEATUNNEL_ROW_KIND: {value: "seatunnel_row_kind", label: "SeaTunnel Row Kind"},
//   SEATUNNEL_FAKE_MODE: {value: "seatunnel_fake_mode", label: "SeaTunnel Fake Mode"},
//   SEATUNNEL_CDC_FORMAT: {value: "seatunnel_cdc_format", label: "SeaTunnel CDC Format"},
//   IMAGE_PULL_POLICY: {value: "image_pull_policy", label: "Image Pull Policy"},
//   WORKFLOW_TYPE: {value: "workflow_type", label: "Workflow Type"},
//   WORKFLOW_EXECUTE_TYPE: {value: "workflow_execute_type", label: "Workflow Execute Type"},
//   WORKFLOW_INSTANCE_STATE: {value: "workflow_instance_state", label: "Workflow Instance State"},
//   WORKFLOW_TASK_TYPE: {value: "workflow_task_type", label: "Workflow Task Type"},
//   WORKFLOW_TASK_INSTANCE_STAGE: {value: "workflow_task_instance_stage", label: "Workflow Task Instance Stage"},
//   SCHEDULE_STATUS: {value: "schedule_status", label: "Schedule Status"},
//   REDIS_MODE: {value: "redis_mode", label: "Redis Mode"},
// })

export enum DeploymentKind {
  Deployment = 'FlinkDeployment',
  SessionCluster = 'FlinkSessionJob'
}

export enum YesOrNo {
  YES = '1',
  NO = '0'
}
